/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as NightRouteImport } from './routes/night'
import { Route as NightsRouteImport } from './routes/nights'
import { Route as ConfirmSlugRouteImport } from './routes/confirm.$slug'
import { Route as PacketIdRouteImport } from './routes/packet.$id'
import { Route as RecordSlugRouteImport } from './routes/record.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const NightRoute = NightRouteImport.update({
  id: '/night',
  path: '/night',
  getParentRoute: () => rootRouteImport,
} as any)
const NightsRoute = NightsRouteImport.update({
  id: '/nights',
  path: '/nights',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmSlugRoute = ConfirmSlugRouteImport.update({
  id: '/confirm/$slug',
  path: '/confirm/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketIdRoute = PacketIdRouteImport.update({
  id: '/packet/$id',
  path: '/packet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordSlugRoute = RecordSlugRouteImport.update({
  id: '/record/$slug',
  path: '/record/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/guide': typeof GuideRoute
  '/night': typeof NightRoute
  '/nights': typeof NightsRoute
  '/confirm/$slug': typeof ConfirmSlugRoute
  '/packet/$id': typeof PacketIdRoute
  '/record/$slug': typeof RecordSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/guide': typeof GuideRoute
  '/night': typeof NightRoute
  '/nights': typeof NightsRoute
  '/confirm/$slug': typeof ConfirmSlugRoute
  '/packet/$id': typeof PacketIdRoute
  '/record/$slug': typeof RecordSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/guide': typeof GuideRoute
  '/night': typeof NightRoute
  '/nights': typeof NightsRoute
  '/confirm/$slug': typeof ConfirmSlugRoute
  '/packet/$id': typeof PacketIdRoute
  '/record/$slug': typeof RecordSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/guide'
    | '/night'
    | '/nights'
    | '/confirm/$slug'
    | '/packet/$id'
    | '/record/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/guide'
    | '/night'
    | '/nights'
    | '/confirm/$slug'
    | '/packet/$id'
    | '/record/$slug'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/guide'
    | '/night'
    | '/nights'
    | '/confirm/$slug'
    | '/packet/$id'
    | '/record/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  GuideRoute: typeof GuideRoute
  NightRoute: typeof NightRoute
  NightsRoute: typeof NightsRoute
  ConfirmSlugRoute: typeof ConfirmSlugRoute
  PacketIdRoute: typeof PacketIdRoute
  RecordSlugRoute: typeof RecordSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night': {
      id: '/night'
      path: '/night'
      fullPath: '/night'
      preLoaderRoute: typeof NightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nights': {
      id: '/nights'
      path: '/nights'
      fullPath: '/nights'
      preLoaderRoute: typeof NightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm/$slug': {
      id: '/confirm/$slug'
      path: '/confirm/$slug'
      fullPath: '/confirm/$slug'
      preLoaderRoute: typeof ConfirmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet/$id': {
      id: '/packet/$id'
      path: '/packet/$id'
      fullPath: '/packet/$id'
      preLoaderRoute: typeof PacketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$slug': {
      id: '/record/$slug'
      path: '/record/$slug'
      fullPath: '/record/$slug'
      preLoaderRoute: typeof RecordSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  GuideRoute: GuideRoute,
  NightRoute: NightRoute,
  NightsRoute: NightsRoute,
  ConfirmSlugRoute: ConfirmSlugRoute,
  PacketIdRoute: PacketIdRoute,
  RecordSlugRoute: RecordSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
